project/cabinet/urls.py
from django.urls import path

from cabinet.views import *

urlpatterns = [
    path('', HomeView.as_view(template_name="home.html"), name="home"),
    path('login/', LoginView.as_view(template_name="login.html"), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('register/', RegisterView.as_view(template_name="register.html"), name="register"),
    path('application/create/', ApplicationCreateView.as_view(template_name="application_create.html"),
         name="create_application"),
    path('profile/', ProfileView.as_view(template_name="profile.html"), name="profile"),
    path("profile/filter/", FilterProfileView.as_view(template_name="profile.html"), name='profile-filter'),
    path('application/delete/<int:pk>', ApplicationDeleteView.as_view(template_name="application_delete.html"),
         name="application_delete"),
    path('application/delete/confirm/<int:pk>',
         ApplicationDeleteConfirmView.as_view(template_name="application_delete.html"),
         name="application_delete_confirm"),
    path('applications/list/', ApplicationListView.as_view(template_name="applications_list.html"),
         name="applications_list"),
    path('application/done/change/<int:pk>/', ApplicationDoneChangeStatusView.as_view(
        template_name="application_done_change_status.html"), name="application_done_change_status"),
    path('application/work/change/<int:pk>/', ApplicationWorkChangeStatusView.as_view(
        template_name="application_work_change_status.html"), name="application_work_change_status"),
    path('categories/list/', CategoryListView.as_view(template_name="categories_list.html"), name="categories_list"),
    path('category/create/', CategoryCreateView.as_view(template_name="category_create.html"), name="create_category"),
    path('category/delete/<int:pk>/', CategoryDeleteView.as_view(), name="category_delete"),
]

project/designpro/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView


from cabinet.views import *
from designpro import settings

urlpatterns = [
    path('superadmin/', admin.site.urls),
    path('cabinet/', include('cabinet.urls')),
    path('', RedirectView.as_view(url='/cabinet/', permanent=True)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/cabinet/models.py
from django.contrib.auth.models import User
from django.core.validators import FileExtensionValidator
from django.db import models

class Category(models.Model):
    title = models.CharField(max_length=255, verbose_name='Название категории')

    def __str__(self):
        return self.title

class Application(models.Model):
    STATUS_CHOICES = [
        ('Н', 'Новая'),
        ('П', 'Принято в работу'),
        ('В', 'Выполнено')
    ]
    created = models.DateTimeField(auto_now_add=True, verbose_name='Временная метка заявки')
    title = models.CharField(max_length=255, verbose_name='Название заявки')
    description = models.TextField(verbose_name='Описание заявки')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория заявки')
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default=STATUS_CHOICES[0][0], verbose_name='Статус заявки')
    image = models.ImageField(upload_to='images/', verbose_name='Фото помещения или план заявки')
    applicant = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Заявитель')
    image_done = models.ImageField(upload_to='images_done/', blank=True, verbose_name='Созданный дизайн')
    comment = models.TextField(blank=True, verbose_name='Комментарий')

    def __str__(self):
        return self.title

project/cabinet/forms.py
from django.contrib.auth.models import User
from django import forms

from cabinet.models import Application, Category


class ConfirmField(forms.Field):
    def validate(self, value):
        super(ConfirmField, self).validate(value)
        if value is None:
            raise forms.ValidationError(
                "Ошибка: "
                "Поставьте галочку о согласии"
            )

class UserForm(forms.ModelForm):
    username = forms.CharField()
    first_name = forms.CharField()
    email = forms.EmailField()  # Используйте EmailField для валидации email
    password = forms.CharField(widget=forms.PasswordInput())
    password2 = forms.CharField(widget=forms.PasswordInput())
    confirm = ConfirmField(required=False)

    class Meta:
        model = User
        fields = ['username', 'first_name', 'email', 'password']

    def clean_password2(self):
        if self.cleaned_data.get("password") != self.cleaned_data.get("password2"):
            raise forms.ValidationError(
                "Ошибка: "
                "введенные пароли не совпадают"
            )

    def clean_first_name(self):
        first_name = self.cleaned_data.get('first_name')
        # Проверка ФИО на кириллические буквы, дефис и пробелы
        if not all(char.isalpha() or char in ('-', ' ') for char in first_name):
            raise forms.ValidationError(
                "Ошибка: "
                "ФИО должно содержать только кириллические буквы, дефис и пробелы"
            )
        return first_name

class ApplicationForm(forms.ModelForm):

    def clean_image(self):
        image = self.cleaned_data.get("image")
        image_size = image.size
        str_file = str(image)
        if str_file.endswith('.jpg') and image_size <= 2097152:
            return image
        elif str_file.endswith('.jpeg') and image_size <= 2097152:
            return image
        elif str_file.endswith('.png') and image_size <= 2097152:
            return image
        elif str_file.endswith('.bpm') and image_size <= 2097152:
            return image
        else:
            raise forms.ValidationError(
                "Ошибка: "
                "Файл должен иметь формат: jpg, jpeg, png, bmp и размер не более 2МБ"
            )
        return file

    class Meta:
        model = Application
        fields = ('title', 'description', 'category', 'image', )

class ApplicationDoneForm(forms.ModelForm):
    image_done = forms.ImageField(label='Созданный дизайн', required=True)

    class Meta:
        model = Application
        fields = ('image_done', )

class ApplicationWorkForm(forms.ModelForm):
    comment = forms.CharField(label='Комментарий', required=True)

    class Meta:
        model = Application
        fields = ('comment', )

class CategoryForm(forms.ModelForm):

    class Meta:
        model = Category
        fields = ('title', )

project/cabinet/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.views.generic.base import TemplateView
from django.contrib.auth import login, authenticate, logout
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from .forms import *


# домашняя
class HomeView(TemplateView):
    def get(self, request, *args, **kwargs):
        applications = Application.objects.filter(status='В').order_by('-created')[:4]
        applications_count = Application.objects.filter(status='П').count()
        context = {'applications': applications, 'applications_count': applications_count}
        return render(request, self.template_name, context)

# регистрация
class RegisterView(TemplateView):
    form_class = UserForm
    success_url = reverse_lazy('home')
    def get(self, request, *args, **kwargs):
        form = self.form_class(None)
        return render(request, self.template_name, locals())

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)

        if form.is_valid(): # проверяем форму регистрации
            user =form.save(commit=False)
            user.first_name = form.cleaned_data['first_name']
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            user = authenticate(username=username, password=password)

            if user is not None and user.is_active:
                login(request,user)
                return HttpResponseRedirect("/")

        return render(request, self.template_name, locals())

# логин
class LoginView(TemplateView):
    success_url = reverse_lazy('home')
    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, locals())

    def post(self, request, *args, **kwargs):
        username = request.POST.get("username")
        password = request.POST.get("password")

        user = authenticate(username=username, password=password)

        if user is not None and user.is_active:
            login(request,user)
            return HttpResponseRedirect("/")
        err = "Неправильное имя пользователя или пароль"
        return render(request, self.template_name, locals())

# выход
class LogoutView(TemplateView):
    success_url = reverse_lazy('home')
    def get(self, request, *args, **kwargs):
        logout(request)
        return HttpResponseRedirect("/")

class ApplicationCreateView(TemplateView, LoginRequiredMixin):
    form_class = ApplicationForm
    def get(self, request, *args, **kwargs):
        form = self.form_class(None)
        return render(request, self.template_name, locals())

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, request.FILES)

        if form.is_valid():  # проверяем форму регистрации
            instance = form.save(commit=False)
            instance.applicant = request.user
            instance.save()
            return redirect('profile')

        return render(request, self.template_name, locals())

class ProfileView(TemplateView, LoginRequiredMixin):
    def get(self, request, *args, **kwargs):
        applications = Application.objects.filter(applicant=request.user).order_by('-created')
        context = {'application_list': applications}
        return render(request, self.template_name, context)

class FilterProfileView(TemplateView, LoginRequiredMixin):
    def get(self, request, *args, **kwargs):
        applications = Application.objects.filter(
            applicant=self.request.user, status=self.request.GET.get('status')[0]).order_by('-created')
        context = {'application_list': applications}
        return render(request, self.template_name, context)

class ApplicationDeleteView(TemplateView, LoginRequiredMixin):
    success_url = reverse_lazy('application_delete_confirm')

    def get(self, request, pk, *args, **kwargs):
        application = Application.objects.get(id=pk)
        if application.status == 'Н':
            return render(request, self.template_name, locals())

class ApplicationDeleteConfirmView(TemplateView, LoginRequiredMixin):
    def get(self, request, pk, *args, **kwargs):
        application = Application.objects.get(id=pk)
        application.delete()
        return redirect('profile')

class ApplicationListView(TemplateView, LoginRequiredMixin):
    def get(self, request, *args, **kwargs):
        applications = Application.objects.filter(status='Н')
        context = {'applications': applications}
        return render(request, self.template_name, context)

class ApplicationDoneChangeStatusView(TemplateView, LoginRequiredMixin):
    form_class = ApplicationDoneForm
    def get(self, request, pk, *args, **kwargs):
        form = self.form_class(None)
        application = Application.objects.get(id=pk)
        context = {'application': application, 'form': form}
        return render(request, self.template_name, context)

    def post(self, request, pk, *args, **kwargs):
        application = Application.objects.get(id=pk)
        form = self.form_class(request.POST, request.FILES, instance=application)

        if form.is_valid():  # проверяем форму регистрации
            instance = form.save(commit=False)
            instance.status = 'В'
            instance.save()
            return redirect('applications_list')

        return render(request, self.template_name, locals())

class ApplicationWorkChangeStatusView(TemplateView, LoginRequiredMixin):
    form_class = ApplicationWorkForm
    def get(self, request, pk, *args, **kwargs):
        form = self.form_class(None)
        application = Application.objects.get(id=pk)
        context = {'application': application, 'form': form}
        return render(request, self.template_name, context)

    def post(self, request, pk, *args, **kwargs):
        application = Application.objects.get(id=pk)
        form = self.form_class(request.POST, instance=application)

        if form.is_valid():  # проверяем форму регистрации
            instance = form.save(commit=False)
            instance.status = 'П'
            instance.save()
            return redirect('applications_list')

        return render(request, self.template_name, locals())

class CategoryListView(TemplateView, LoginRequiredMixin):
    def get(self, request, *args, **kwargs):
        categories = Category.objects.all()
        context = {'categories': categories}
        return render(request, self.template_name, context)

class CategoryCreateView(TemplateView, LoginRequiredMixin):
    form_class = CategoryForm
    def get(self, request, *args, **kwargs):
        form = self.form_class(None)
        return render(request, self.template_name, locals())

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)

        if form.is_valid():  # проверяем форму регистрации
            form.save()
            return redirect('categories_list')

        return render(request, self.template_name, locals())

class CategoryDeleteView(TemplateView, LoginRequiredMixin):
    def get(self, request, pk, *args, **kwargs):
        category = Category.objects.get(id=pk)
        category.delete()
        return redirect('categories_list')

project/cabinet/templates/application_create.html
{% extends "base.html" %}

{% block title %}Создание заявки{% endblock %}

{% block content %}


<div class="row">
	<div class="col-md-4"></div>
	<div class="col-md-4">
		<h3>Создание заявки</h3>
		<form method="POST" class = "sign-up-form" enctype="multipart/form-data">
			{% csrf_token %}
            <div>
        {% for field in form %}
        <div class="form-group">
            {{field.label_tag}}
            <div>{{field}}</div>
            {% if field.errors%}
            {% for err in field.errors %}
                <span class="invalid-feedback">{{ err }}</span>{{error}}
            {% endfor %}
            {% endif %}
        </div>
        {% endfor %}
        </div>

		<input type="submit" class="btn btn-primary" value="Создать заявку" />
		</form>
</div>
</div>
{% endblock %}

project/cabinet/templates/application_delete.html
{% extends "base.html" %}
{% block content %}
<h3>Вы уверены, что хотите удалить заявку?</h3>
<a href="{% url 'application_delete_confirm' pk=application.id %}" class="btn btn-primary">Подтвердить</a>
{% endblock %}

project/cabinet/templates/application_done_change_status.html
{% extends "base.html" %}

{% block title %}Изменение статуса заявки{% endblock %}

{% block content %}


<div class="row">
	<div class="col-md-4"></div>
	<div class="col-md-4">
		<h3>Изменение статуса заявки на "Выполнено"</h3>
        <p>Название заявки: {{ application.title }}</p>
		<form method="POST" class = "sign-up-form" enctype="multipart/form-data">
			{% csrf_token %}
            <div>
        {% for field in form %}
        <div class="form-group">
            {{field.label_tag}}
            <div>{{field}}</div>
            {% if field.errors%}
            {% for err in field.errors %}
                <span class="invalid-feedback">{{ err }}</span>{{error}}
            {% endfor %}
            {% endif %}
        </div>
        {% endfor %}
        </div>

		<input type="submit" class="btn btn-primary" value="Изменить статус заявки" />
		</form>
</div>
</div>
{% endblock %}

project/cabinet/templates/application_work_change_status.html
{% extends "base.html" %}

{% block title %}Изменение статуса заявки{% endblock %}

{% block content %}


<div class="row">
	<div class="col-md-4"></div>
	<div class="col-md-4">
		<h3>Изменение статуса заявки на "Принято в работу"</h3>
        <p>Название заявки: {{ application.title }}</p>
		<form method="POST" class = "sign-up-form">
			{% csrf_token %}
            <div>
        {% for field in form %}
        <div class="form-group">
            {{field.label_tag}}
            <div>{{field}}</div>
            {% if field.errors%}
            {% for err in field.errors %}
                <span class="invalid-feedback">{{ err }}</span>{{error}}
            {% endfor %}
            {% endif %}
        </div>
        {% endfor %}
        </div>

		<input type="submit" class="btn btn-primary" value="Изменить статус заявки" />
		</form>
</div>
</div>
{% endblock %}

project/cabinet/templates/applications_list.html
{% extends "base.html" %}
{% block content %}
<h3>Страница для работы со статусами заявок</h3>

<p>Все заявки со статусом "Новая":</p>
<ul>
    {% for application in applications %}
      <li>Название заявки: {{ application.title }}</li>
        <a href="{% url 'application_work_change_status' pk=application.id %}" class="btn btn-primary">Изменить статус заявки на "Принято в работу"</a>
        <a href="{% url 'application_done_change_status' pk=application.id %}" class="btn btn-primary">Изменить статус заявки на "Выполнено"</a>
      <p>-----------------------------------------</p>
    {% endfor %}
</ul>
{% endblock %}

project/cabinet/templates/categories_list.html
{% extends "base.html" %}
{% block content %}
<h3>Страница для работы с категориями</h3>

<a href="{% url 'create_category' %}" class="btn btn-primary">Создать категорию</a>

<p>Все категории:</p>
<ul>
    {% for category in categories %}
      <li>Название категории: {{ category.title }}</li>
        <a href="{% url 'category_delete' pk=category.id %}" class="btn btn-primary">Удалить категорию</a>
      <p>-----------------------------------------</p>
    {% endfor %}
</ul>
{% endblock %}

project/cabinet/templates/category_create.html
{% extends "base.html" %}

{% block title %}Создание заявки{% endblock %}

{% block content %}


<div class="row">
	<div class="col-md-4"></div>
	<div class="col-md-4">
		<h3>Создание заявки</h3>
		<form method="POST" class = "sign-up-form">
			{% csrf_token %}
            <div>
        {% for field in form %}
        <div class="form-group">
            {{field.label_tag}}
            <div>{{field}}</div>
            {% if field.errors%}
            {% for err in field.errors %}
                <span class="invalid-feedback">{{ err }}</span>{{error}}
            {% endfor %}
            {% endif %}
        </div>
        {% endfor %}
        </div>

		<input type="submit" class="btn btn-primary" value="Создать категорию" />
		</form>
</div>
</div>
{% endblock %}

project/cabinet/templates/home.html
{% extends "base.html" %}
{% block content %}
<h3>Домашняя страница</h3>
<h4>Здравствуйте!</h4>
<p>Список 4-х последних выполненых заявок:</p>
<ul>
    {% for application in applications %}
        <li>Временная метка:{{ application.created }}</li>
        <li>Название:{{ application.title }}</li>
        <li>Категория заявки:{{ application.category }}</li>
        <li>Фотография: <img src="{{ application.image.url }}" alt="application photo" style="height:100px; width:100px"></li>
    {% endfor %}
</ul>
<p>Количество заявок находящихся в работе: {{ applications_count }}</p>
{% endblock %}

project/cabinet/templates/login.html
{% extends "base.html" %}

{% block title %}Вход{% endblock %}

{% block content %}
<div class="row">
	<div class="col-md-4"></div>
	<div class="col-md-4">
		<h3>Вход</h3>
		<form method="POST" class = "sign-up-form">
			{% csrf_token %}
		<div class="form-group">
		  <label for="username">
		    Логин
		  </label>
		  <input type="text" id="username"  name="username" class="form-control">
		</div>

		<div class="form-group">
		  <label for="password">
		    Пароль
		  </label>
		  <input type="password" id="password" name="password" class="form-control"/>
		</div>


		  {% if err %}
		    <span class="invalid-feedback">{{ err }}</span>
		  {% endif %}

		<input type="submit" class="btn btn-primary" value="Войти" />
		</form>
	</div>
</div>
{% endblock %}

project/cabinet/templates/profile.html
{% extends "base.html" %}
{% block content %}
<h3>Профиль пользователя</h3>
<h4>Здравствуйте, {{ request.user.first_name }}!</h4>

<form action="{% url 'profile-filter' %}" method="get" name="filter">
  <h3>Статус заявки:</h3>
    <div>
        <select name="status">
            <option value="Н">Новая</option>
            <option value="П">Принято в работу</option>
            <option value="В">Выполнено</option>
        </select>
    </div>
    <br>
    <button type="submit" class="btn btn-primary">Найти</button>
</form>
<br>
<a href="{% url 'profile' %}" class="btn btn-primary">Показать все</a>
<br>
<p>Ваши заявки:</p>
<ul>
    {% for application in application_list %}
      <li>Временная метка: {{ application.created }}</li>
      <li>Название заявки: {{ application.title }}</li>
      <li>Описание заявки: {{ application.description }}</li>
      <li>Категория заявки: {{ application.category }}</li>
      <li>Статус заявки: {{ application.get_status_display }}</li>
        {% if application.status == 'Н' %}
            <a href="{% url 'application_delete' pk=application.id %}" class="btn btn-primary">Удалить заявку</a>
        {% elif application.status == 'П' %}
		    <span class="invalid-feedback"><i><strong>*</strong>Вы не можете удалить данную заявку, так как она принята в работу.</i></span>
        {% elif application.status == 'В' %}
		    <span class="invalid-feedback"><i><strong>*</strong>Вы не можете удалить данную заявку, так как она выполнена.</i></span>
        {% endif %}
      <p>-----------------------------------------</p>
    {% endfor %}
</ul>
{% endblock %}

project/cabinet/templates/register.html
{% extends "base.html" %}

{% block title %}Регистрация{% endblock %}

{% block content %}


<div class="row">
	<div class="col-md-4"></div>
	<div class="col-md-4">
		<h3>Регистрация</h3>
		<form method="POST" class = "sign-up-form">
			{% csrf_token %}

		<div class="form-group">
		  <label for="{{ form.first_name.id_for_label }}">
		    Фамилия Имя Отчество
		  </label>
		  <input type="text" id="{{ form.first_name.id_for_label }}"
		         name="{{ form.first_name.html_name }}"
		         {% if form.first_name.field.required %}required{% endif %}
		         class="form-control{% if form.first_name.errors %} is-invalid{% endif %}"
		         value="{% if form.first_name.value %}{{ form.first_name.value }}{% endif %}">
		  {% if form.first_name.help_text %}
		    <small class="text-muted">
		      {{ form.first_name.help_text }}
		    </small>
		  {% endif %}
		  {% for err in form.first_name.errors %}
		    <span class="invalid-feedback">{{ err }}</span>
		  {% endfor %}
		</div>

		<div class="form-group">
		  <label for="{{ form.username.id_for_label }}">
		    Логин
		  </label>
		  <input type="text" id="{{ form.username.id_for_label }}"
		         name="{{ form.username.html_name }}"
		         {% if form.username.field.required %}required{% endif %}
		         class="form-control{% if form.username.errors %} is-invalid{% endif %}"
		         value="{% if form.username.value %}{{ form.username.value }}{% endif %}">
		  {% if form.username.help_text %}
		    <small class="text-muted">
		      {{ form.username.help_text }}
		    </small>
		  {% endif %}
		  {% for err in form.username.errors %}
		    <span class="invalid-feedback">{{ err }}</span>
		  {% endfor %}
		</div>


		<div class="form-group">
		  <label for="{{ form.email.id_for_label }}">
		    Email
		  </label>
		  <input type="email" id="{{ form.email.id_for_label }}"
		         name="{{ form.email.html_name }}"
		         {% if form.email.field.required %}required{% endif %}
		         class="form-control{% if form.email.errors %} is-invalid{% endif %}"
		         value="{% if form.email.value %}{{ form.email.value }}{% endif %}">
		  {% if form.email.help_text %}
		    <small class="text-muted">
		      {{ form.email.help_text }}
		    </small>
		  {% endif %}
		  {% for err in form.email.errors %}
		    <span class="invalid-feedback">{{ err }}</span>
		  {% endfor %}
		</div>


		<div class="form-group">
		  <label for="{{ form.password.id_for_label }}">
		    Пароль
		  </label>
		  <input type="password" id="{{ form.password.id_for_label }}"
		         name="{{ form.password.html_name }}"
		         {% if form.password.field.required %}required{% endif %}
		         class="form-control{% if form.password.errors %} is-invalid{% endif %}"
		         value="{% if form.password.value %}{{ form.password.value }}{% endif %}">
		  {% if form.password.help_text %}
		    <small class="text-muted">
		      {{ form.password.help_text }}
		    </small>
		  {% endif %}
		  {% for err in form.password.errors %}
		    <span class="invalid-feedback">{{ err }}</span>
		  {% endfor %}
		</div>

		<div class="form-group">
		  <label for="{{ form.password2.id_for_label }}">
		    Повтор пароля
		  </label>
		  <input type="password" id="{{ form.password2.id_for_label }}"
		         name="{{ form.password2.html_name }}"
		         {% if form.password2.field.required %}required{% endif %}
		         class="form-control{% if form.password2.errors %} is-invalid{% endif %}"
		         value="{% if form.password2.value %}{{ form.password2.value }}{% endif %}">
		  {% if form.password2.help_text %}
		    <small class="text-muted">
		      {{ form.password2.help_text }}
		    </small>
		  {% endif %}
		  {% for err in form.password2.errors %}
		    <span class="invalid-feedback">{{ err }}</span>
		  {% endfor %}
		</div>

		<div class="form-group">
		  <label for="confirm" >
		  	<input type="checkbox" id="confirm" value="1" name="confirm"/>
		    Согласие на обработку персональных данных
		  </label>
		  
		  {% if form.confirm.help_text %}
		    <small class="text-muted">
		      {{ form.confirm.help_text }}
		    </small>
		  {% endif %}
		  {% for err in form.confirm.errors %}
		    <span class="invalid-feedback">{{ err }}</span>
		  {% endfor %}
		</div>

		<input type="submit" class="btn btn-primary" value="Зарегистрироваться" />
		</form>
</div>
</div>
{% endblock %}